HeatingSystemWebApp/Controllers/LoginController.cs
using System;
using System.Web.Mvc;
using HeatingSystemModel.Model;
using HeatingSystemModel.Storage;
using System.Linq;

namespace HeatingSystemWebApp.Controllers
{
    public class LoginController : Controller
    {

        // GET: Login
        public ActionResult Index()
        {
            return View();
        }


    }
}

HeatingSystemWebApp/Controllers/MeterReadingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HeatingSystemModel.Model;
using HeatingSystemModel.Storage;
using HeatingSystemModel.Service;

namespace HeatingSystemWebApp.Controllers
{
    public class MeterReadingsController : Controller
    {
        private StorageContext db = new StorageContext();

        // GET: MeterReadings
        public ActionResult Index(int meterId)
        {
            return View(db.MeterReadings.Where(m => m.Meter.Id == meterId).ToList().OrderBy(m => m.Date.Year).ToList());
        }

        // GET: MeterReadings/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MeterReading meterReading = db.MeterReadings.Find(id);
            if (meterReading == null)
            {
                return HttpNotFound();
            }
            return View(meterReading);
        }

        // GET: MeterReadings/Create
        public ActionResult Create()
        {
            return View();
        }

        // GET: MeterReadings/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MeterReading meterReading = db.MeterReadings.Find(id);
            if (meterReading == null)
            {
                return HttpNotFound();
            }
            return View(meterReading);
        }

        // POST: MeterReadings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,kWh,CubeMeters,UsageHours")] MeterReading meterReading)
        {
            if(meterReading != null) { 
                int _id = Service.UpdateMeterReading(meterReading);
                return RedirectToAction("Index","ReadingAcknowledging", new { meterId = _id,meterReadingId = meterReading.Id });
            }
            return View(meterReading);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HeatingSystemWebApp/Controllers/ReadingAcknowledgingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Mvc;
using HeatingSystemModel.Storage;
using HeatingSystemModel.Model;

namespace HeatingSystemWebApp.Controllers
{
    public class ReadingAcknowledgingController : Controller
    {
        public ActionResult Index(int meterId,int meterReadingId)
        {
            string textDisplayed = "";
            if (meterId == 0)
            {
               textDisplayed = "Failed to update the reading";
            }
            else
            {
                using (var db = new StorageContext())
                {
                    
                    var actualMeterReading = db.MeterReadings.Where(mr => mr.Id == meterReadingId).FirstOrDefault();
                    var lastMeterReading = db.MeterReadings.Where(mr => mr.Meter.Id == meterId && mr.Id != meterReadingId && mr.Date.Year<actualMeterReading.Date.Year).OrderBy(mr => mr.Date.Year).FirstOrDefault();
                    if (lastMeterReading != null && actualMeterReading != null)
                    {
                        double lastMeterReadingKWH = lastMeterReading.kWh;
                        double actualMeterReadingKWH = actualMeterReading.kWh;

                        double percentage = (actualMeterReadingKWH / lastMeterReadingKWH) * 100;

                        if (percentage > 30)
                            textDisplayed = "This year consumption is " +percentage.ToString()+ "% higher than last registration! Make sure data is inserted correctly";
                    }
                    if (textDisplayed == "")
                        textDisplayed = "Succesfully updated the meter reading";
                }
            }
            @ViewBag.MyLabelAck = textDisplayed;
            return View();
        }

    }
}

HeatingSystemWebApp/Views/Login/Index.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
</head>
<body>
    <div>
      @using (@Html.BeginForm("Index", "MeterReadings"))
      {
        <label>Please enter your meter unique id</label>
        <input type="number" min="1" name="meterId" required/>
        <input type="submit" value="Proceed to the readings">
      }

      
    </div>
</body>
</html>

HeatingSystemWebApp/Views/MeterReadings/Details.cshtml
@model HeatingSystemModel.Model.MeterReading

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>MeterReading</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.kWh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.kWh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CubeMeters)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CubeMeters)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UsageHours)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UsageHours)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index", new { meterId = Model.Meter.Id } )
</p>

HeatingSystemWebApp/Views/MeterReadings/Edit.cshtml
@model HeatingSystemModel.Model.MeterReading

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MeterReading</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.kWh, htmlAttributes: new {@class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.kWh, new { htmlAttributes = new {@type = "number", @min = "0", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.kWh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CubeMeters, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CubeMeters, new {htmlAttributes = new {@type = "number", @min = "0", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CubeMeters, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UsageHours, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UsageHours, new {htmlAttributes = new {@type = "number", @min = "0", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UsageHours, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { meterId = Model.Meter.Id } )
</div>

HeatingSystemWebApp/Views/MeterReadings/Index.cshtml
@model IEnumerable<HeatingSystemModel.Model.MeterReading>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.kWh)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CubeMeters)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UsageHours)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    if (item.isEnabled) { 
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.kWh)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CubeMeters)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UsageHours)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>

        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) 
        </td>
    </tr>
    }
}
</table>

HeatingSystemWebApp/Views/ReadingAcknowledging/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<body>
    @using (@Html.BeginForm("Index", "Login"))
    {
        <div>
            <h2>Customer acknoledgment</h2>
            <label name="lblAck">@ViewBag.MyLabelAck</label>
        </div>
        <input type="submit" value="Proceed to the login page">
    }

</body>

HeatingSystemWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("HeatingSystem", "Index", "Login", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - SCHOOL ASSIGNMENT - BUSINESS ACADEMY AARHUS</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>